# Generated by Django 4.1.2 on 2022-10-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_ongs_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongs',
            name='logo',
            field=models.ImageField(null=True, upload_to='fotos/'),
        ),
    ]
