# Generated by Django 4.1.2 on 2022-10-05 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_ongs_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ongs',
            name='password',
        ),
    ]
