# Generated by Django 4.1.2 on 2022-10-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cnpj',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.ImageField(null=True, upload_to='', verbose_name='fotos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
