# Generated by Django 4.1.2 on 2022-10-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_cnpj_user_cpf_user_logo_user_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='cnpj',
            field=models.CharField(max_length=14, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(null=True, upload_to='fotos/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.CharField(max_length=13, null=True, verbose_name='Telefone'),
        ),
    ]
