# Generated by Django 4.1.2 on 2022-10-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_descricao_alter_user_cnpj_alter_user_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='descricao',
            field=models.TextField(default='Sua ajuda pode mudar muitas vidas.'),
        ),
    ]
