# Generated by Django 4.1.2 on 2022-10-10 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_cpf_alter_user_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_org',
        ),
    ]
